spring.application.name=biblioteca-api
server.port=9090

spring.datasource.url=jdbc:postgresql://db.byjjlnftgclifhrtqylm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=bibli.oteca
spring.datasource.driver-class-name=org.postgresql.Driver
