spring.application.name=biblioteca-api
server.port=9090

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.byjjlnftgclifhrtqylm
spring.datasource.password=bibli.oteca
spring.datasource.driver-class-name=org.postgresql.Driver
